### ISSUE TITLE
Unable to negate a style on a subset of text

### ISSUE THREAD

**Issue by ninjamar** [ninjamar/editor#22]
Unable to negate a style on a subset of text

**Comment by ninjamar** [comment]
Get all styles applied to current element (prob above extractGreatestParent)
If style contains current option
 Then set option to the inverse of the current option (eg bold to unbold)


Proceed normally

**Comment by ninjamar** [comment]
I got the solution to work, however strikethrough and underline both use `text-decoration`, which doesn't have a way to negate.
I figured out a workaround, which is likely very buggy.
```css
.line {
    text-decoration: line-through;
    text-decoration-skip: object;
}
.no-line {
     display: inline-block;
}
```
